// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1j-1cVJw8S5r2m9aR9aJrA0etG9P0Xtc',
    appId: '1:59418746043:web:263bcce36a9e50d42e5d9e',
    messagingSenderId: '59418746043',
    projectId: 'anything-that-i-like',
    authDomain: 'anything-that-i-like.firebaseapp.com',
    storageBucket: 'anything-that-i-like.appspot.com',
    measurementId: 'G-JK5WQYT63C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC2hTCTCzualmUo6X1ubwwt3fCeWXFZCY',
    appId: '1:59418746043:android:d57f0044ff71908b2e5d9e',
    messagingSenderId: '59418746043',
    projectId: 'anything-that-i-like',
    storageBucket: 'anything-that-i-like.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6fRwDK3cL8p4x66DAtxdKDUNYryPFhQ',
    appId: '1:59418746043:ios:b2810ba089e3b0c72e5d9e',
    messagingSenderId: '59418746043',
    projectId: 'anything-that-i-like',
    storageBucket: 'anything-that-i-like.appspot.com',
    iosBundleId: 'com.example.anythingThatILike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl6fRwDK3cL8p4x66DAtxdKDUNYryPFhQ',
    appId: '1:59418746043:ios:b2810ba089e3b0c72e5d9e',
    messagingSenderId: '59418746043',
    projectId: 'anything-that-i-like',
    storageBucket: 'anything-that-i-like.appspot.com',
    iosBundleId: 'com.example.anythingThatILike',
  );
}
